# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1f0f92648dfc653626aa5b35c90213e74f717ca83103a6a2e07aa7c131d2b5aba34adcbf0ccb157b9e88e32026de75de7a39481fdf299c523bc627fd0b2af45

test:
  secret_key_base: 0a874ff7dd6624335eb8cde9844bbef9473e63e654b799b52d288b8d1edd1ad0125403c4b71c3e151ed5b50a80cbad74f448bfdf7a7bb69eb21c02ed6619e1d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
